# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
gems:                [jekyll-paginate]
paginate:            5
paginate_path:       "page:num"

# Setup
title:            Julia
tagline:          'A Jekyll theme'
description:      'Erasmus University Rotterdam'
url:             
baseurl:          /

author:
  name:           'Julia K'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           
