# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Julia
tagline:          'A Jekyll theme'
description:      'Erasmus University Rotterdam'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Julia K'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
